services:
  - type: web
    name: dearnekitchen
    runtime: python
    rootDir: DearneKitchen
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate --no-input && python manage.py seed_initial_data
    startCommand: gunicorn DearneKitchen.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: "False"
