# Generated by Django 5.2.15 on 2026-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
