# Generated by Django 5.2.15 on 2026-06-09 09:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_alter_booktable_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='itemlist',
            options={'verbose_name_plural': 'Item categories'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='booktable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booktable',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='Phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='Total_person',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='User_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='Category_name',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'item')},
        ),
        migrations.AddIndex(
            model_name='booktable',
            index=models.Index(fields=['Booking_date', 'status'], name='Base_App_bo_Booking_455c12_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='Base_App_ca_user_id_f36966_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='Base_App_fe_created_f60c91_idx'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['Item_name'], name='Base_App_it_Item_na_3778ee_idx'),
        ),
        migrations.AddIndex(
            model_name='items',
            index=models.Index(fields=['Category', 'Item_name'], name='Base_App_it_Categor_bd6ac2_idx'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base_App.items'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Base_App.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='Base_App_or_user_id_2cffa4_idx'),
        ),
    ]
